"""A module to represent the game state and logic.
"""


class Game:
    """
    A class to represent the game state.
    Attributes:
        life (int): The number of lives the player has.
        score (int): The player's current score.
        altered_regions (list[tuple[int, int, int, int]]): A list of tuples representing
            the regions that have been altered.
            The tuple format is (x, y, width, height).
        found_regions (list[tuple[int, int, int, int]]): A list of tuples representing
            the regions that have been found by the player.
            The tuple format is (x, y, width, height).
    Functions:

    """
    def __init__(self, altered_regions: list[tuple[int, int, int, int]]):
        """Instance initialisation, sets the score to 0 then calls start_game
        to setup the game state for a new game.

        Args:
            altered_regions: Generated by ImageProcessor
                The tuple format is (x, y, width, height)
        """
        self.score = 0
        self.start_game(altered_regions)

    def start_game(self, altered_regions: list[tuple[int, int, int, int]]) -> None:
        """Initialises the game state for a new game.
        Args:
            altered_regions: Generated by ImageProcessor
                The tuple format is (x, y, width, height)
        """
        self.life = 3
        self.altered_regions = altered_regions
        self.found_regions = []

    def guess(self, x, y) -> None:
        """Processes a player's guess at the given coordinates.
        Args:
            x: The x-coordinate of the guess.
            y: The y-coordinate of the guess.
        """
        if self.life <= 0:
            return  # Ran out of lives, don't process guess

        correct_guess = False
        for region in self.altered_regions:
            # Check if the guess is within the altered region
            if region[0] <= x <= region[0] + region[2] and region[1] <= y <= region[1] + region[3]:
                if region in self.found_regions:
                    correct_guess = True
                    return  # Already found this region, skip the guess
                self.found_regions.append(region)
                self.score += 1
                return

        if not correct_guess:
            self.life -= 1  # Incorrect guess, lose a life
