"""A module to represent the game state and logic.
"""


class Game:
    """
    A class to represent the game state.
    Attributes:
        life (int): The number of lives the player has.
        score (int): The player's current score.
        altered_regions (list[tuple[int, int, int, int]]): A list of tuples representing
            the regions that have been altered.
            The tuple format is (x, y, width, height).
        found_regions (list[tuple[int, int, int, int]]): A list of tuples representing
            the regions that have been found by the player.
            The tuple format is (x, y, width, height).
        revealed (bool): A flag to indicate if player has chosen to reveal all altered regions.
    Functions:
        __init__(self, altered_regions: list[tuple[int, int, int, int]]): Initializes the game state.
        start_game(self, altered_regions: list[tuple[int, int, int, int]]) -> None: Sets up the game state for a new game.
        guess(self, x, y) -> None: Processes a player's guess at the given coordinates.
        get_game_state(self) -> dict: Returns the current game state as a dictionary.
        get_all_altered_regions(self) -> list[tuple[int, int, int, int]]: Returns a list of all altered regions in the game.

    """
    def __init__(self, altered_regions: list[tuple[int, int, int, int]]):
        """Instance initialisation, sets the score to 0 then calls start_game
        to setup the game state for a new game.

        Args:
            altered_regions: Generated by ImageProcessor
                The tuple format is (x, y, width, height)
        """
        self.score = 0
        self.start_game(altered_regions)

    def start_game(self, altered_regions: list[tuple[int, int, int, int]]) -> None:
        """Initialises the game state for a new game.
        Args:
            altered_regions: Generated by ImageProcessor
                The tuple format is (x, y, width, height)
        """
        self.life = 3
        self.altered_regions = altered_regions
        self.found_regions = []
        self.revealed = False

    def guess(self, x, y) -> None:
        """Processes a player's guess at the given coordinates.
        Args:
            x: The x-coordinate of the guess.
            y: The y-coordinate of the guess.
        """
        if self.life <= 0 or self.revealed:
            return  # Ran out of lives/game is done, don't process guess

        for region in self.altered_regions:
            # Check if the guess is within the altered region
            if region[0] <= x <= region[0] + region[2] and region[1] <= y <= region[1] + region[3]:
                if region in self.found_regions:
                    return  # Already found this region, skip the guess
                self.found_regions.append(region)
                self.score += 1
                return

        self.life -= 1  # Incorrect guess, lose a life

    def get_game_state(self) -> dict:
        """Returns the current game state as a dictionary.
        Returns:
            A dictionary containing the current score, lives, and found regions.
        """
        return {
            'score': self.score,
            'life': self.life,
            'found_regions': self.found_regions,
            'revealed': self.revealed
        }
    
    def get_all_altered_regions(self) -> list[tuple[int, int, int, int]]:
        """Returns a list of all altered regions in the game.
        Returns:
            A list of tuples representing all altered regions.
            The tuple format is (x, y, width, height).
        """
        return self.altered_regions

    def reveal(self) -> None:
        """Reveals all altered regions to the player."""
        self.revealed = True
    
    
